from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys

class MyWindow(QMainWindow):  #inherit from QMainWindow
    def __init__(self):
        super(MyWindow, self).__init__()    
        self.setGeometry(200, 200, 558, 254) #((location window shows)(dimensions))
        self.setWindowTitle("Media Player")   
        self.initUI()
    
    def initUI(self):
        self.centralwidget = QtWidgets.QWidget(MyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lab_med_player = QtWidgets.QLabel(self.centralwidget)
        self.lab_med_player.setGeometry(QtCore.QRect(10, 0, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_med_player.setFont(font)
        self.lab_med_player.setObjectName("lab_med_player")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 20, 651, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.inp_title = QtWidgets.QLineEdit(self.centralwidget)
        self.inp_title.setGeometry(QtCore.QRect(90, 40, 261, 21))
        self.inp_title.setAccessibleName("")
        self.inp_title.setObjectName("inp_title")
        self.inp_year = QtWidgets.QLineEdit(self.centralwidget)
        self.inp_year.setGeometry(QtCore.QRect(440, 40, 101, 21))
        self.inp_year.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.inp_year.setObjectName("inp_year")
        self.inp_url = QtWidgets.QLineEdit(self.centralwidget)
        self.inp_url.setGeometry(QtCore.QRect(90, 100, 451, 21))
        self.inp_url.setObjectName("inp_url")
        self.inp_artist = QtWidgets.QLineEdit(self.centralwidget)
        self.inp_artist.setGeometry(QtCore.QRect(90, 70, 261, 21))
        self.inp_artist.setObjectName("inp_artist")
        self.inp_genre = QtWidgets.QLineEdit(self.centralwidget)
        self.inp_genre.setGeometry(QtCore.QRect(440, 70, 101, 21))
        self.inp_genre.setObjectName("inp_genre")
        self.lab_title = QtWidgets.QLabel(self.centralwidget)
        self.lab_title.setGeometry(QtCore.QRect(10, 40, 81, 16))
        self.lab_title.setAutoFillBackground(False)
        self.lab_title.setObjectName("lab_title")
        self.lab_year = QtWidgets.QLabel(self.centralwidget)
        self.lab_year.setGeometry(QtCore.QRect(360, 40, 71, 20))
        self.lab_year.setObjectName("lab_year")
        self.lab_artist = QtWidgets.QLabel(self.centralwidget)
        self.lab_artist.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.lab_artist.setObjectName("lab_artist")
        self.lab_genre = QtWidgets.QLabel(self.centralwidget)
        self.lab_genre.setGeometry(QtCore.QRect(360, 70, 81, 16))
        self.lab_genre.setObjectName("lab_genre")
        self.lab_url = QtWidgets.QLabel(self.centralwidget)
        self.lab_url.setGeometry(QtCore.QRect(10, 100, 71, 16))
        self.lab_url.setObjectName("lab_url")
        self.but_play = QtWidgets.QPushButton(self.centralwidget)
        self.but_play.setGeometry(QtCore.QRect(10, 160, 113, 32))
        self.but_play.setObjectName("but_play")
        self.but_pause = QtWidgets.QPushButton(self.centralwidget)
        self.but_pause.setGeometry(QtCore.QRect(120, 160, 113, 32))
        self.but_pause.setObjectName("but_pause")
        self.but_replay = QtWidgets.QPushButton(self.centralwidget)
        self.but_replay.setGeometry(QtCore.QRect(230, 160, 113, 32))
        self.but_replay.setObjectName("but_replay")
        self.but_load = QtWidgets.QPushButton(self.centralwidget)
        self.but_load.setGeometry(QtCore.QRect(430, 130, 113, 32))
        self.but_load.setObjectName("but_load")
        self.format = QtWidgets.QComboBox(self.centralwidget)
        self.format.setGeometry(QtCore.QRect(330, 130, 101, 31))
        self.format.setObjectName("format")
        self.format.addItem("")
        self.format.addItem("")
        MyWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MyWindow)
        QtCore.QMetaObject.connectSlotsByName(MyWindow)

    def retranslateUi(self, MyWindow):
        _translate = QtCore.QCoreApplication.translate
        MyWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab_med_player.setText(_translate("MainWindow", "Media Player"))
        self.lab_title.setText(_translate("MainWindow", "Input Title:"))
        self.lab_year.setText(_translate("MainWindow", "Input Year:"))
        self.lab_artist.setText(_translate("MainWindow", "Input Artist:"))
        self.lab_genre.setText(_translate("MainWindow", "Input Genre:"))
        self.lab_url.setText(_translate("MainWindow", "Input URL:"))
        self.but_play.setText(_translate("MainWindow", "Play"))
        self.but_pause.setText(_translate("MainWindow", "Pause"))
        self.but_replay.setText(_translate("MainWindow", "Replay"))
        self.but_load.setText(_translate("MainWindow", "Load"))
        self.format.setItemText(0, _translate("MainWindow", ".wav"))
        self.format.setItemText(1, _translate("MainWindow", ".mp3"))

def window():
    app = QApplication(sys.argv) 
    win = QtWidgets.QMainWindow()
    win.show()
    sys.exit(app.exec_())

window()   #run window function